# TODO: Test components independently
- name: master
  run_list:
  - recipe[mapr::kitchen_helper]
  - recipe[mapr::smart_install]
  verifier:
    inspect-test: test/integration/master
  attributes:
    mapr:
      config:
        mode: 0444 # Due to bug in KITCHEN-EC2 we can't change the username with which we are connecting, so to see if
        # do actually create anything, we need to enlarge the permissions of the configuration files
        # Ref: https://github.com/test-kitchen/kitchen-ec2/issues/225
      cluster:
        components:
        - cldb
        - mcs
        - zookeeper

- name: master-with-kerberos
  run_list:
  - recipe[mapr::kitchen_helper]
  - recipe[mapr::smart_install]
  verifier:
    inspect-test: test/integration/master-with-kerberos
  attributes:
    mapr:
      config:
        mode: 0444 # Due to bug in KITCHEN-EC2 we can't change the username with which we are connecting, so to see if
        # do actually create anything, we need to enlarge the permissions of the configuration files
        # Ref: https://github.com/test-kitchen/kitchen-ec2/issues/225
      cluster:
        components:
        - cldb
        - mcs
        - zookeeper
        - resourcemanager
        - compute
        - storage
        - mfs
        config:
          security:
            secure: true
            kerberosEnable: true
            cldbPrincipal: mapr/mapr.cluster.com