language: ruby
cache: bundler
rvm:
- 2.4.0
deploy:
  skip_cleanup: true
  edge:
    source: criteo-forks/dpl
    branch: chef_ruby2
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Applications
  client_key: ".travis/client.pem"
  on:
    tags: true
env:
  global:
  - secure: H9VmhwTCt8T9Yy0K6EuTCREGuE382tdg+C7Lj4bTyZDTxKTpJUmpunl62o2MmrtLnhEAEJw408G9QUHdVf0mAW1X/D2s0tXvCi4o4Ljit7oRoWgZVD/q3m5b3U36VUoICFFJlYIU8rm+JvbCI6Zfab1IkkTtp0r5Xr+TTzoY6CXSvHhTKL+NJJe11Ev6yzWHatTiXQs7Y/ydzRmS4m31BM7b1xeMTAQF0vQ+IpoC7Nocui1JeXslk40ccMZCl0zH3ngPm9IrlP+aik1fsoltRPhD6C8Fgo8w9hjl4yek6ikMLNvBPTUp59PkL9+2ji62IFFwJhqlUPIFD5S6fI8wpK1O/9Nhxc8zDLdnmW06o9KaE8bT9guqnZ0iUABmiYIoUZ5uFbJnnUW+jfBHRyBdfflBvy4IabRdHLKjwgdTe37UTb5qOvhq4cLMQnWVvIvOM1Bs6O7cgkcUB/MDK2CBYfVW4Zf+cAnmvSsO2XWnJUmzKQVgk78VMooXkNy8f6fzjXmCfVxGQjcWaEjsZCC9H8iZZPFvj0LiD6GwMAU8jgwdzx+eaG0sQAJ28LTc8x7AMD8KG8aYLMvIwnMl8YxLRpWYC3QJwR2d3gYLf+i9LmZwgO4o1m43pvEQpPaU33OWCMzgR0zpShn7U4ocTLxp10Y7zaV0bAlmkjFIZVmaHIE=
  - secure: JRrk4r9X+TlhQjskhRwq26EbI+Omscon945em3v0q2tXT0sxnnFuK1STjzYR4K0ddGljyiyW8RwazV5CRn02VnBg5gwLfmvStnENaZklAf+qjxP6b1c91SeCl3k9GKVpu6YSepslppQzqMIbc8bNkZ9zoctpWix11VG4vANb3ryyTezHkIegfj4W+8DzJz1rFhbRSXmv8cTML5cZST4I+zOjrWiwIbdKILX1nsOkYbf09qRDVBO3Ge6RBPGHP8Gt/IfMzyQ2LM2/pwOhe7giSumnMS3bLGpjBr8iI+ByC4YDUzBoGu+qMjRRugcuubD11gFE+b7N+0ydR9eV4T+AW8nEcRpjGwzd8D26s4z1sbYSTjuYOdmfTfVkY33Gt3JGiX7j0jgsOCEzOQ9Ta30fbY+gUdq93+pDzqPbMOz4wqY1ruT6XpsTHBwb5usOiwZX+FBkIuueleIvFU00aI8rtI5p2GKJTOs84KcFoDBykT8zSkPZ7Dpa+jUlvvOmvxYREwQ7hg5/7lfSM+aa7AMqPUXHCOP02V88sbk4OSncD2BcEMEo72zHQNGL6NlRg4cUOy4MZALC/IgaD/XvzIe/GnMKt/RYnCO+2d47XdreoowISR0QCfiWfudgV29oUknPFIEe4l38E5UutjLe+YudLmhEvHRec1k6xb3TL3qFFso=
  - secure: x/ru7u/Dxh2B22J2AU8cxcBsTEQx7AMgBp9AKNJgjFiJRy7mh51Q3+NYyEtvlGW94CC3fu5mATeeVTacjRzM7Hk6MDKE0O16go7IFp9DtYgkFeIZi9JY7naRDhdGDCxitM2iSmApnvS7o71z563EHYh6sqZxv/YeFnnc0tIFOZqmT3+370WemjTtMkU4DmcvkUlcowudcYkOhzOzCcaC8A6B+Ohyoh8POLe0wm9I4Hg8kE4HNuVtvTlvAiPc4UisboNSKCm6YTjTSC3SOdHDvc0UytkRxgtJQZShhC0OQ6cKsoWcAVfAhIUzswDgYlAd3q42keRjB//ZVITC+lyu2qmr4VIHl7KNgX9chT2zZ0V2seInhetFb0mXzjZpPH+H4TSb/kzsKPBvaCK3uOJXZmq735+hMnSVd0Ee85ZGLIuyjuV8JwBoF89iiR1la+2OcBFpB7x7Pod2urK9q3e1vAjQIRUxSxBB/zJkFhMtMy2C0obj50zWG9B4w1k1LLEd49UeFvJqI0u5L3Lz5OSyDApQnHy/ztjNxEFPe1KzSY/lpVAry1m3gwJlHu2Bi7t+PYxmzp64KkkR4pTYL7imJKcJ9oHF0by3yJkT3npPuuadOevZ/xjbFUcd0U/rq7l9t21K0NcEeoLlB97GmcXUOvKwqw74/tUHKWDv3gifBbM=
  - secure: swqTBgrRuZS9/mzJz0vQDu6gNKDf7oXJwUYJzPSn8+tMFdURz9nwQpc23JBE8fMMBokwX8WbN6qSjgjJWy4D/U9CP2rTNLOVlX6h1tsQq4uKnUiWQnyIMI5pHw/Hpf+iytpSVSkK5JyLvT7QnWKkl1lev2VTasWXBMCWHrSegeLGhEy5FqvXqq/gtD327YB7iWv5In/fPqJbt2hO0Ok9G9KggUj3668D2tYei2cle3nPkpSAqqjGXP034NfHqmOmvYquJXLL1hqsABy9lq4jzZBQQ0eLsbCYsL1j9IDsyAuVhcqBPKK7U0nj+7C3bDjinqP/gszAeqGbHEeoSgszfXv9KNWOtWYleZ1CZ+q3SlBxIpUcMqaPW7qHHsuBPFUWzu9pVgwA24uSoEyvCzwsfvUtGi3ZfUgeKSXxRzNY5rMZI9HFi7/Hakr6n1AF7BcpxoGF8EPfpF3kX+r6O40bwFIDDKmdeW94opbGYQYmgqSoVHFXVXaN52eAQ5SseqKGsS2EC6rDoy9AeC7gY+uXs8wzl/MGzyrYoTK8n9lDUd7ikypvJEWJkSYsX09ReIuBCw7OjhXXhI+r5a8ifi80owMf8CdAoAnnDXHn4aAbrKYiiwV6J/Nv7Gd7/4wB9xDoRZqPr4Ti1GWWeweAX4Cb/YHZVEbCJuPgh+AqgZBiXWk=
before_deploy:
- openssl aes-256-cbc -K $encrypted_eb3fc2d5c3da_key -iv $encrypted_eb3fc2d5c3da_iv
  -in .travis/client.pem.enc -out .travis/client.pem -d
before_install:
- '[ -n "$encrypted_eb3fc2d5c3da_iv" ] && openssl aes-256-cbc -K $encrypted_eb3fc2d5c3da_key
  -iv $encrypted_eb3fc2d5c3da_iv -in .travis/travis-ci.pem.enc -out .travis/travis-ci.pem.criteo
  -d'
- "[ -f .travis-ci.pem.criteo ] && cp -v .travis-ci.pem.criteo ~/.ssh/id_rsa"
- yes | gem update --system --force
- gem install bundler