name             'mapr'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'All rights reserved'
description      'MapR cookbook'
long_description 'Install and configure MapR'
issues_url       'https://github.com/criteo-cookbooks/mapr/issues'
source_url       'https://github.com/criteo-cookbooks/mapr'
version          '0.0.1'
supports         'centos'
