name             'mapr'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'All rights reserved'
description      ''
long_description ''
issues_url       ''
source_url       'https://github.com/criteo-cookbooks/mapr'
version          '0.0.0'
supports         'centos'
