default['mapr']['warden']['mastgateway']['config'] = {
    'services' => 'mastgateway:all:cldb',
    'service.displayname' => 'MASTGatewayService',
    'service.command.start' => '/opt/mapr/initscripts/mapr-mastgateway start',
    'service.command.stop' => '/opt/mapr/initscripts/mapr-mastgateway stop',
    'service.command.type' => 'BACKGROUND',
    'service.command.monitorcommand' => '/opt/mapr/initscripts/mapr-mastgateway status',
    'service.port' => 8660,
    'service.baseservice' => 1,
    'service.logs.location' => '/opt/mapr/logs/mastgateway.log',
    'service.process.type' => 'JAVA',
    'service.heapsize.min' => 2048,
    'service.heapsize.max' => 20480,
    'service.heapsize.percent' => 10,
}